### ISSUE TITLE
Check Constraints - Use of Between 

### ISSUE THREAD

**Issue by sarahj3344** [w0527452/350-assignment08#3]
https://github.com/w0527452/350-assignment08/blob/849c3f8b8bbd52c02fa9d6219a49d985585fe48c/assignment08.sql#L57

I don't think the between operator will work for this problem. Correct me if I am wrong, but I think 0 and 99.99 should be included in allowed values but using between excludes these values. The iacademy website is down right now so I can't double check, hopefully it's running in the morning and I can run script again.

**Comment by w0527452** [comment]
You might be onto something, Sarah.  I think I only tried it with values extremely out of range.

What do you recommend doing here?

**Comment by sarahj3344** [comment]
UPDATE -- I think I figured out how to use the pull request! Did I do this correctly? 

Oh boy... this is a lot to take in. Trying to figure out how to show you the change. Should I do it through a pull request? I saw you made a new branch for dynamic insert. Is it bad etiquette to add the code here or should I make a new branch for check constraints?
